# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{coal}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aiden Nibali"]
  s.date = %q{2010-05-15}
  s.description = %q{Low-level language which may be embedded in Ruby code}
  s.email = %q{dismal.denizen@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "lib/coal.rb",
     "lib/coal.treetop",
     "lib/coal/extras/math.rb",
     "lib/coal/translators/libjit.rb",
     "lib/coal/translators/ruby.rb",
     "lib/virtmem.rb",
     "spec/arithmetic_spec.rb",
     "spec/assignment_spec.rb",
     "spec/bitwise_spec.rb",
     "spec/extras/math_spec.rb",
     "spec/if_unless_spec.rb",
     "spec/parser_spec.rb",
     "spec/pointer_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8", "--title", "coal 0.0.0\n", "--main", "README", "--line-numbers"]
  s.require_paths = ["lib"]
  s.requirements = ["libjit"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Low-level language which may be embedded in Ruby code}
  s.test_files = [
    "spec/if_unless_spec.rb",
     "spec/assignment_spec.rb",
     "spec/bitwise_spec.rb",
     "spec/parser_spec.rb",
     "spec/pointer_spec.rb",
     "spec/spec_helper.rb",
     "spec/extras/math_spec.rb",
     "spec/arithmetic_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mixin>, [">= 0.7.0"])
      s.add_runtime_dependency(%q<treetop>, [">= 1.4.0"])
    else
      s.add_dependency(%q<mixin>, [">= 0.7.0"])
      s.add_dependency(%q<treetop>, [">= 1.4.0"])
    end
  else
    s.add_dependency(%q<mixin>, [">= 0.7.0"])
    s.add_dependency(%q<treetop>, [">= 1.4.0"])
  end
end

